
// include::config_vars.adoc[])

===  Check that Ansible is installed

In the first part we will setup the bastion host as a simple
admin server.

. Update the bastion host
+
[subs=attributes+]
----
# ssh {jumpuser}@{jumphost-ext} -i ~/.ssh/mylab
# sudo -i
# dnf -y update
# reboot
----
. Connect to the control node ({jumphost}):
+
[subs=attributes+]
----
# ssh {jumpuser}@{jumphost-ext}
----
. Check that Ansible is installed and usable:
+
[subs=attributes+]
-----
$ ansible --version
ansible 2.9.11
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Oct 11 2019, 15:04:54) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
-----

. Check that the environment variable GUID is set
+
[subs=attributes+]
-----
$ env| grep GUID
GUID=a1fe
-----

=== Check the Prerequisites

NOTE: Ansible is keeping configuration management simple. Ansible requires no database or running daemons and can run easily on a laptop. On the managed hosts it needs no running agent.

Verify that the managed hosts accept password-less connections with key authentication from {adminhost} as user {admin}, e.g.:

[subs=attributes+]
----
[{admin}@{adminhost} ~]$ ssh {servera}
[{admin}@{servera} ~]$ exit
----

[subs=attributes+]
----
[{admin}@{adminhost} ~]$ ssh {serverb}
[{admin}@{serverb} ~]$ exit
----

To allow user {admin} to execute commands on {servera} and {serverb} as root `sudo` needs to be configured on the managed hosts.

Test that the configuration allows {admin} to run commands using `sudo` on {servera} and {serverb} without a password, e.g.:

[subs=attributes+]
----
[{admin}@{adminhost} ~]$ ssh {servera}
[{admin}@{servera} ~]$ sudo cat /etc/shadow
[{admin}@{servera} ~]$ exit
----

NOTE: *In all subsequent exercises you should work as the user {admin} on the bastion host (jumphost) if not explicitly told differently.*

=== Create a working directory for playbooks and configuration files

Make sure you are user {admin} on {adminhost}. Create a directory for your ansible files:

[subs=attributes+]
----
[{admin}@{adminhost} ~]$ mkdir ansible-files
----

=== Configure the inventory

In this Lab the inventory is already configured globally in `/etc/ansible/hosts` .
The hana servers are group in the group `hana`, the S/4HANA server is named `s4hana`

* Run `ansible all --list-hosts` -- You will see an output similar to this:
+
[subs=attributes+]
----
[{admin}@{adminhost} ansible-files]$ ansible all --list-hosts
  hosts (2):
    {servera-fqdn}
    {serverb-fqdn}
----

* Use ansible ping to check the connections from your management hosts
+
[subs=attributes+]
----
[{admin}@{adminhost} ansible-files]$ ansible -m ping all
{servera-fqdn} | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
{serverb-fqdn} | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
----
