Ansible on SAP Training Guide
=============================
:scrollbar:
:data-uri:
:toc: left
:numbered:
:icons: font
:imagesdir: ./images


## Overview
After this lab you will have a basic understanding of how ansible works and how to use and modify the predefined ansible roles

To use this Lab you have to be a Redhat partner and do have access to Red Hat Online Partner Enablement Network (OPEN)

TIP: If you do not have an account on OPENTLC or do not remember your username or password, https://account.opentlc.com/account/activateAccountForm.php[activate your account or reset your credentials].

Before you can run these labs, you need to prepare the access to the lab environment and then provision it.

## Prepare Access to Lab environment

Before you provision your lab environment you want to make sure that you can connect to your servers after the provisioning. This can be achieved via ssh public-keys or kerberos.

### Setup SSH
To access the jumphost via SSH, use your personal OPENTLC SSO username and public SSH key.

NOTE: Unless otherwise noted, you cannot use SSH to connect directly as root.

If you have not already done so, you must provide a public SSH key.

 . Go to https://www.opentlc.com/update and log in.
 . Paste your public key in the appropriate field.

TIP: For more information on generating an SSH key, see: https://www.opentlc.com/ssh.html[Setting Up an SSH Key Pair].

### Use Kerberos Authentication Instead of SSH Keys (Advanced)
If you have problems using SSH keys, use Kerberos authentication instead. To do this you must be running on a UNIX/Linux or macOS host.

NOTE: Windows hosts can support Kerberos, but it is beyond the scope of this class to provide instructions for implementing it.

1. Make sure you have the following settings in `/etc/krb5.conf` on your host (not in the lab environment):

  dns_lookup_realm = true
  dns_lookup_kdc = true

2. Use the following command to obtain a Kerberos ticket:

   $ kinit your-sso-login@OPENTLC.COM
   <enter your OPENTLC SSO password>

IMPORTANT: Capitalize all letters of OPENTLC.COM, as shown.

## Provison your Lab environments

In this training we use two Lab Environments on RHPDS one smaller for ansible and a more compley
## Provision the Ansible Lab Environment

 1. Access the https://labs.opentlc.com/[OPENTLC lab portal], which is built on top of Red Hat CloudForms.
 2. Use your credentials to log in.
 3. After you log in, navigate to *Services → Catalogs → All Services → OPENTLC Cloud Infrastructure Labs*.
 4. On the left side of the screen, locate *Ansible Foundations Lab* and click *Order*, which appears on the right.
 5. On the next screen, on the lower right side, click Submit to order your Ansible Foundations environment.
 6. Check your email for a message from Red Hat describing how to connect to the environment.
 7. Wait about 20 minutes to allow the environment to build.

## Provision the HANA Lab environment

1. Access the https://labs.opentlc.com/[OPENTLC lab portal], which is built on top of Red Hat CloudForms.
 2. Use your credentials to log in.
 3. After you log in, navigate to *Services → Catalogs → All Services → OPENTLC Datacenter Infrastructure Labs*.
 4. On the left side of the screen, locate *RHEL for SAP HANA 7 Lab* and click *Order*, which appears on the right.
 5. On the next screen, on the lower right side, click Submit to order your Ansible Foundations environment.
 6. Check your email for a message from Red Hat describing how to connect to the environment.
 7. Wait about 20 minutes to allow the environment to build.

### Upload your HANA express to this Lab environment

## Access Environment With SSH

To access your control host:

1. Look up your *GUID* in the Email you have received
2. Open a terminal session
3. Log in to your control host with your OPENTLC SSO username and your private ssh key or kerberos ticket

   # ssh  your-sso-login@workstation-GUID.rhpds.opentlc.com

NOTE: You might need to specify the previously created private key of the ssh keypair with `-i  path-to-your-private-ssh-key` if not using your default keypair

NOTE: When entering commands, replace GUID with your personal GUID, which is provided at the top of the lab provisioning email you received from Red Hat.

IMPORTANT: To avoid problems, always use the FQDN hostname and not the IP or Ravello DNS entry when using SSH to connect to your OPENTLC lab hosts.

////
## Start with the Ansible Lab

Now continue with link:ansible-engine_short.html[this lab guide]

////
include::ansible-engine_short.adoc[]
